import streamlit as st
import PyPDF2
from fpdf import FPDF
import os

st.set_page_config(page_title="ReviewMyCV", layout="wide")



def generate_pdf_report(score, matched, missing, fit_level):
    pdf = FPDF()
    pdf.add_page()


    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, "ReviewMyCV: Analysis Report", ln=True, align='C')
    pdf.ln(10)


    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, f"Match Score: {score}%", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(200, 10, f"Fit Level: {fit_level}", ln=True)
    pdf.ln(5)


    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, "Matched Skills:", ln=True)
    pdf.set_font("Arial", '', 10)
    if matched:
        for s in matched:
            pdf.cell(200, 8, f"- {s}", ln=True)
    else:
        pdf.cell(200, 8, "- None detected", ln=True)
    pdf.ln(5)

    # Missing Skills
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, "Missing Skills (Gaps):", ln=True)
    pdf.set_font("Arial", '', 10)
    if missing:
        for s in missing:
            pdf.cell(200, 8, f"x {s}", ln=True)
    else:
        pdf.cell(200, 8, "- No gaps found!", ln=True)

    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(200, 10, "Report generated by ReviewMyCV Optimizer", align='C')

    return pdf.output(dest='S').encode('latin-1')


st.markdown("""
<style>
    #MainMenu {visibility:hidden;}
    footer {visibility:hidden;}
    header {visibility:hidden;}
    .stApp { background-color: #f8fff8; }
    .stButton>button {
        background-color: #39ff14;
        color: #000;
        font-weight: bold;
        border-radius: 10px;
        width: 100%;
        border: none;
        height: 50px;
        transition: 0.3s transform ease;
    }
    .stButton>button:hover {
        transform: translateY(-2px);
        background-color: #32e612;
        color: #000;
    }
    .stProgress > div > div > div > div { background-color: #39ff14; }
    [data-testid="stMetricValue"] { color: #1b5e20; }
</style>
""", unsafe_allow_html=True)


st.markdown("<h1 style='text-align: left; color: #000000;'>ReviewMyCV</h1>", unsafe_allow_html=True)
st.markdown("<p style='color: #666;'>Optimize your application with logic-driven skill matching.</p>",
            unsafe_allow_html=True)


with st.expander("Try with Demo Files"):
    st.write("Download these samples to test the app logic immediately:")
    d_col1, d_col2 = st.columns(2)

    resume_path = "demo_samples/resumes/standard_resume.pdf"
    jd_path = "demo_samples/job_descriptions/sample_job.txt"

    with d_col1:
        if os.path.exists(resume_path):
            with open(resume_path, "rb") as f:
                st.download_button("Download Sample Resume", f, "standard_resume.pdf", use_container_width=True)
        else:
            st.warning("Sample resume not found.")

    with d_col2:
        if os.path.exists(jd_path):
            with open(jd_path, "r") as f:
                st.download_button("Download Sample JD", f.read(), "sample_job.txt", use_container_width=True)
        else:
            st.warning("Sample JD not found.")

st.markdown("---")

col_left, col_right = st.columns([1, 1], gap="large")

with col_left:
    st.subheader("1. Your Resume")
    uploaded_file = st.file_uploader("Upload PDF", type=["pdf"])

    resume_text = ""
    is_scanned_pdf = False

    if uploaded_file:
        reader = PyPDF2.PdfReader(uploaded_file)
        for page in reader.pages:
            content = page.extract_text()
            if content:
                resume_text += content

        if len(resume_text.strip()) < 100:
            is_scanned_pdf = True
            st.error("⚠️ Scanned PDF Detected")
            st.info("Please upload a text-based PDF. Scanned images cannot be analyzed.")
        else:
            st.success("Resume loaded successfully!")

with col_right:
    st.subheader("2. Job Details")
    job_desc = st.text_area("Paste Job Description", height=150, placeholder="Paste the full job post here...")

st.markdown("---")

SKILL_MAP = {
    "Python Ecosystem": ["python", "py", "pandas", "numpy", "django", "flask", "fastapi", "pytorch", "tensorflow"],
    "Java/Backend": ["java", "spring boot", "maven", "hibernate", "microservices", "spring", "j2ee"],
    "Web Frontend": ["react", "next.js", "javascript", "typescript", "tailwind", "css", "html", "vue", "angular"],
    "Database Systems": ["sql", "mysql", "postgresql", "mongodb", "nosql", "redis", "database", "query"],
    "Cloud & Infrastructure": ["aws", "azure", "gcp", "docker", "kubernetes", "cloud", "devops", "cicd", "terraform"],
    "AI/ML Engineering": ["machine learning", "ml", "nlp", "llm", "opencv", "scikit-learn", "deep learning"],
    "Project Management": ["agile", "scrum", "jira", "documentation", "leadership", "teamwork", "sdlc"]
}

if st.button("Run Match Analysis"):
    if is_scanned_pdf:
        st.error("Please upload a text-readable PDF before running the analysis.")
    elif not resume_text or not job_desc:
        st.error("Please provide both a Resume and a Job Description.")
    else:
        job_text_lower = job_desc.lower()
        resume_text_lower = resume_text.lower()

        required_categories = []
        matched_categories = []
        missing_categories = []
        match_details = {}

        for category, synonyms in SKILL_MAP.items():
            jd_triggers = [s for s in synonyms if s in job_text_lower]
            if jd_triggers:
                required_categories.append(category)
                resume_triggers = [s for s in synonyms if s in resume_text_lower]
                if resume_triggers:
                    matched_categories.append(category)
                    match_details[category] = resume_triggers[0]
                else:
                    missing_categories.append(category)

        if not required_categories:
            st.warning("No technical keywords detected in the JD. Try a more detailed description.")
        else:
            score = int((len(matched_categories) / len(required_categories)) * 100)
            fit_level = "Strong Match" if score >= 75 else "Moderate Match" if score >= 50 else "Needs Improvement"
            fit_color = "green" if score >= 75 else "orange" if score >= 50 else "red"

            st.markdown(f"### Analysis Results")
            m1, m2, m3 = st.columns(3)
            m1.metric("Match Score", f"{score}%")
            m2.metric("Skills Found", f"{len(matched_categories)}/{len(required_categories)}")
            m3.markdown(f"**Fit Level:**\n#### :{fit_color}[{fit_level}]")

            st.progress(score / 100)

            res_col1, res_col2 = st.columns(2)
            with res_col1:
                with st.expander("✅ Matched Skills", expanded=True):
                    if matched_categories:
                        for s in matched_categories:
                            st.write(f"✔️ **{s}** (Found: *{match_details[s]}*)")
                    else:
                        st.write("No direct matches found.")

            with res_col2:
                with st.expander(" Missing Skills", expanded=True):
                    if missing_categories:
                        for s in missing_categories:
                            st.markdown(f"<span style='color:#e74c3c;'>✘ {s}</span>", unsafe_allow_html=True)
                    else:
                        st.success("You have all required categories!")

            st.markdown("---")
            st.subheader("Save Your Results")
            pdf_data = generate_pdf_report(score, matched_categories, missing_categories, fit_level)
            st.download_button("Download Analysis Report (PDF)", pdf_data, "ReviewMyCV_Report.pdf", "application/pdf",
                               use_container_width=True)

            st.markdown("---")
            st.subheader("Optimize Your Resume with AI")


            ai_prompt = f"""
Act as a Senior Tech Recruiter. I have analyzed my resume against a Job Description using ReviewMyCV. 

**Analysis Summary:**
- Match Score: {score}%
- Fit Level: {fit_level}
- Skills Found: {', '.join(matched_categories) if matched_categories else 'None'}
- Critical Skill Gaps: {', '.join(missing_categories) if missing_categories else 'None'}

**Your Instructions:**
1. Based on the score, give me one brutal piece of advice to improve my resume's relevance.
2. Provide 3 high-impact bullet points I can add to my "Projects" section to cover these gaps: {', '.join(missing_categories)}.
3. Generate 5 behavioral interview questions specifically tailored to this role and my current skill set.

**[RESUME TEXT]:**
{resume_text[:2000]}... (Text truncated for length)

**[JOB DESCRIPTION]:**
{job_desc}
"""
            st.write("Copy this pre-engineered prompt into ChatGPT or Gemini:")
            st.code(ai_prompt, language="markdown")

st.markdown("---")
st.caption("Privacy First: All processing is done locally. No data is saved.")